#ifndef __SETTING_MENU_ID_H__
#define __SETTING_MENU_ID_H__
#define ENABLE_ENC_TYPE_SELECT
typedef struct __third_icon
{
    const char * icon_name;
}third_icon;
#define THIRD_ICON_NUM 14
static third_icon third_icon_[]=
{
	{"select_on"},
	{"select_on_h"},
	{"select_off"},
	{"select_m"},
	{"subswitch_on"},
	{"subswitch_on_h"},
	{"subswitch_off"},
	{"subswitch_off_h"},
	{"enlarge"},
	{"enlarge_h"},
	{"subsetting"},
	{"subsetting_h"},
	{"upload"},
	{"upload_h"},
};
enum
{
   SELECT_ON =0,
   SELECT_ON_H,
   SELECT_OFF,
   SELECT_M,
   SUBSWITCH_ON,
   SUBSWITCH_ON_H,
   SUBSWITCH_OFF,
   SUBSWITCH_OFF_H,
   ENLARGE,
   ENLARGE_H,
   SUBSETTING,
   SUBSETTING_H,
   UPLOAD,
   UPLOAD_H,
};

#define SETTING_MENU_ID_BASE                 128

enum SETTING_ITEM_ID{
SETTING_RECORD_RESOLUTION = (SETTING_MENU_ID_BASE+1),   //129
SETTING_REAR_RECORD_RESOLUTION     ,
SETTING_RECORD_VOLUME              ,
SETTING_TIMEWATERMARK         		,
SETTING_ACCOUNT_BINDING,
SETTING_SCREEN_BRIGHTNESS          ,
SETTING_CAMERA_AUTOSCREENSAVER     ,
SETTING_EMER_RECORD_SWITCH         ,
SETTING_VOICE_TAKE_PHOTO           ,
SETTING_WIFI_SWITCH                ,
SETTING_4G_NET_WORK					,
SETTING_DEVICE_TIME                ,
SETTING_ACC_SWITCH          ,
SETTING_ADAS_SWITCH                ,
SETTING_WATCH_DOG_SWITCH           ,
SETTING_PARKING_MONITORY           ,
SETTING_STANDBY_CLOCK              ,
SETTING_SYSTEM_SOUND             	,
SETTING_DRIVERING_REPORT_SWITCH    ,
SETTING_DEVICE_LANGUAGE            ,
SETTING_DEVICE_DEVICEINFO          ,
SETTING_DEVICE_SDCARDINFO          ,
SETTING_DEVICE_VERSIONINFO         ,
SETTING_EMER_RECORD_SENSITIVITY     ,     
SETTING_RECORD_LOOP                  ,	
SETTING_DEVICE_RESETFACTORY           ,   
SETTING_PARKING_RECORD_LOOP_RESOLUTION ,  
SETTING_PARKING_WARN_LAMP_SWITCH    ,
SETTING_PARKING_ABNORMAL_MONITORY_SWITCH ,
SETTING_PARKING_ABNORMAL_NOTICE_SWITCH   ,
SETTING_PARKING_RECORD_LOOP_SWITCH    ,
SETTING_KEY_SOUND_SWITCH              ,
SETTING_POWERON_SOUND_SWITCH          ,
SETTING_PROBE_PROMPT             		,
SETTING_SPEED_PROMPT             		,
SETTING_VOLUME_SELECTION             ,
SETTING_SCREEN_NOT_DISTURB_MODE ,
SETTING_FORWARD_COLLISION_WARNING, 
SETTING_LANE_SHIFT_REMINDING ,
SETTING_RECORD_TIMELAPSE      ,       
SETTING_RECORD_SLOWMOTION      ,      
SETTING_PHOTO_RESOLUTION        ,     
SETTING_PHOTO_TIMED              ,    
SETTING_PHOTO_AUTO                ,   
SETTING_PHOTO_DRAMASHOT              ,
SETTING_CAMERA_EXPOSURE            ,  
SETTING_CAMERA_WHITEBALANCE         , 
SETTING_CAMERA_IMAGEROTATION         ,
SETTING_CAMERA_LIGHTSOURCEFREQUENCY  ,
SETTING_CAMERA_LEDINDICATOR          ,
SETTING_CAMERA_TIMEDSHUTDOWN         ,
SETTING_CAMERA_TIMEWATERMARK   ,      
SETTING_CAMERA_DISTORTIONCALIBRATION ,
SETTING_DEVICE_DATETIME              ,
SETTING_DEVICE_FORMAT                ,
SETTING_ACCOUNT_UNBIND              ,
SETTING_DEVICE_VOICESTATUS           ,
#ifdef ENABLE_ENC_TYPE_SELECT
 SETTING_RECORD_ENCODINGTYPE  ,       
#endif
  
SETTING_CAMB_PREVIEWING			, 
SETTING_ACC_RESUME               ,    
SETTING_MOTION_DETECT,
};


enum SETTING_USB_ID{
#define SETTING_USB_CHARGE_MODE  =(SETTING_MENU_ID_BASE+100),
#define SETTING_USB_MASS_STORAGE_MODE  ,
#define SETTING_USB_PCCAM_MODE  ,
};
#define SETTING_USB_NUMBER                   3


#define SETTING_ITEM_DD
#ifdef SETTING_ITEM_DD
static enum SETTING_ITEM_ID setting_item_dd_ids[] =
{
	SETTING_RECORD_RESOLUTION		   ,
//	SETTING_SCREEN_BRIGHTNESS		   ,
	SETTING_CAMERA_AUTOSCREENSAVER	   ,
	SETTING_SYSTEM_SOUND			   ,
	SETTING_ADAS_SWITCH                ,
	SETTING_ACCOUNT_BINDING            ,
    SETTING_DEVICE_DEVICEINFO		   ,
//	SETTING_DEVICE_SDCARDINFO		   ,
    //SETTING_DEVICE_LANGUAGE 		   ,
	SETTING_DEVICE_VERSIONINFO		   ,
//	SETTING_WIFI_SWITCH 		       ,
//	SETTING_DEVICE_TIME 			   ,
//	SETTING_ACC_SWITCH				   ,
};
#define SETTING_RECOR_NUMBER                 (sizeof(setting_item_dd_ids)/sizeof(SETTING_RECORD_RESOLUTION))
#endif
/*
* for setting new windown 
*/


static  SETTING_ITEM_ID listview_item_ids[] =
{
    SETTING_RECORD_RESOLUTION ,
//    SETTING_REAR_RECORD_RESOLUTION     ,
    SETTING_RECORD_LOOP                 ,
    SETTING_RECORD_ENCODINGTYPE,
    SETTING_CAMERA_EXPOSURE,
    SETTING_PARKING_MONITORY    ,
    SETTING_EMER_RECORD_SENSITIVITY,
    SETTING_CAMERA_AUTOSCREENSAVER     ,
    SETTING_DEVICE_LANGUAGE,
    SETTING_RECORD_VOLUME,
    SETTING_VOLUME_SELECTION,
	SETTING_MOTION_DETECT,
    SETTING_CAMERA_LIGHTSOURCEFREQUENCY,
    SETTING_DEVICE_DATETIME,
    SETTING_DEVICE_FORMAT,
    SETTING_DEVICE_RESETFACTORY,
    SETTING_DEVICE_DEVICEINFO,
};

#define SETTING_LISTVIEW_NUM   (sizeof(listview_item_ids)/sizeof(SETTING_RECORD_RESOLUTION))



#endif // __SETTING_MENU_ID_H__
