obj-$(CONFIG_COMPONENTS_RPBUF) += rpbuf_core.o
obj-$(CONFIG_COMPONENTS_RPBUF_SERVICE_RPMSG) += rpbuf_service_rpmsg.o
obj-$(CONFIG_COMPONENTS_RPBUF_CONTROLLER) += rpbuf_controller.o
obj-$(CONFIG_COMPONENTS_RPBUF_RPMSG_DEMO) += rpbuf_demo/
