LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

OBJS_c := dhd_priv.c
L_CFLAGS := -DANDROID

include $(CLEAR_VARS)
LOCAL_MODULE := dhd_priv
LOCAL_MODULE_TAGS := debug tests
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_SHARED_LIBRARIES := libcutils
LOCAL_CFLAGS = $(L_CFLAGS)
LOCAL_SRC_FILES := $(OBJS_c)
LOCAL_C_INCLUDES := $(INCLUDES)
include $(BUILD_EXECUTABLE)
