
#ifndef _SAMPLE_RECORDERCALLBACKOUT_CONFIG_H_
#define _SAMPLE_RECORDERCALLBACKOUT_CONFIG_H_

#define SAMPLE_RECORDERCALLBACKOUT_KEY_CAPTURE_WIDTH    "capture_width"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_CAPTURE_HEIGHT   "capture_height"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_CAPTURE_FORMAT   "capture_format"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_PREVIEW_WIDTH    "preview_width"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_PREVIEW_HEIGHT   "preview_height"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_PREVIEW_FORMAT   "preview_format"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_CAPTURE_BUF_NUM  "capture_buf_num"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_PREVIEW_BUF_NUM  "preview_buf_num"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_FRAME_RATE       "frame_rate"

#define SAMPLE_RECORDERCALLBACKOUT_KEY_PREVIEW_DISPLAY_WIDTH    "preview_display_width"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_PREVIEW_DISPLAY_HEIGHT   "preview_display_height"

#define SAMPLE_RECORDERCALLBACKOUT_KEY_PREVIEW_ENABLE   "preview_enable"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_ENCODE_ENABLE    "encode_enable"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_DISPLAY_FRAME_RATE   "display_frame_rate"

#define SAMPLE_RECORDERCALLBACKOUT_KEY_ENCODE_TYPE      "encode_type"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_ENCODE_WIDTH     "encode_width"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_ENCODE_HEIGHT    "encode_height"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_ENCODE_BITRATE   "encode_bitrate"

#define SAMPLE_RECORDERCALLBACKOUT_KEY_SUB_ENCODE_TYPE      "sub_encode_type"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_SUB_ENCODE_WIDTH     "sub_encode_width"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_SUB_ENCODE_HEIGHT    "sub_encode_height"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_SUB_ENCODE_BITRATE   "sub_encode_bitrate"

#define SAMPLE_RECORDERCALLBACKOUT_KEY_AUDIO_ENCODE_TYPE    "audio_encode_type"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_AUDIO_SAMPLE_RATE    "audio_sample_rate"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_AUDIO_CHANNEL_NUM    "audio_channel_num"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_AUDIO_ENCODE_BITRATE "audio_encode_bitrate"

#define SAMPLE_RECORDERCALLBACKOUT_KEY_ENCODE_DURATION  "encode_duration"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_ENCODE_FOLDER    "encode_folder"

#define SAMPLE_RECORDERCALLBACKOUT_KEY_FILE_PATH        "file_path"
#define SAMPLE_RECORDERCALLBACKOUT_KEY_FILE_PATH2       "file_path2"

#endif  /* _SAMPLE_RECORDERCALLBACKOUT_CONFIG_H_ */

