
#ifndef _SAMPLE_CAMERA_CONFIG_H_
#define _SAMPLE_CAMERA_CONFIG_H_

#define SAMPLE_CAMERA_KEY_CAPTURE_WIDTH     "capture_width"
#define SAMPLE_CAMERA_KEY_CAPTURE_HEIGHT    "capture_height"
#define SAMPLE_CAMERA_KEY_VI_CLOCK          "vi_clock"
#define SAMPLE_CAMERA_KEY_DIGITAL_ZOOM      "digital_zoom"
#define SAMPLE_CAMERA_KEY_PIC_FORMAT        "pic_format"
#define SAMPLE_CAMERA_KEY_FRAME_NUM         "frame_num"
#define SAMPLE_CAMERA_KEY_FRAME_RATE        "frame_rate"
#define SAMPLE_CAMERA_KEY_DISPLAY_FRAME_RATE    "display_frame_rate"
#define SAMPLE_CAMERA_KEY_DISPLAY_WIDTH     "disp_width"
#define SAMPLE_CAMERA_KEY_DISPLAY_HEIGHT    "disp_height"
#define SAMPLE_CAMERA_KEY_PREVIEW_MIRROR    "preview_mirror"
#define SAMPLE_CAMERA_KEY_PREVIEW_ROTATION    "preview_rotation"
#define SAMPLE_CAMERA_KEY_SWITCH_RENDER_TIMES   "switch_render_times"

#define SAMPLE_CAMERA_KEY_REGION_X     "region_x"
#define SAMPLE_CAMERA_KEY_REGION_Y    "region_y"
#define SAMPLE_CAMERA_KEY_REGION_WIDTH    "region_width"
#define SAMPLE_CAMERA_KEY_REGION_HEIGHT   "region_height"

#define SAMPLE_CAMERA_KEY_ANTISHAKE_ENABLE          "antishake_enable"
#define SAMPLE_CAMERA_KEY_ANTISHAKE_INPUT_BUFFERS   "antishake_input_buffers"
#define SAMPLE_CAMERA_KEY_ANTISHAKE_OUTPUT_BUFFERS  "antishake_output_buffers"
#define SAMPLE_CAMERA_KEY_ANTISHAKE_OPERATION_MODE  "antishake_operation_mode"

#define SAMPLE_CAMERA_KEY_JPEG_WIDTH    "jpeg_width"
#define SAMPLE_CAMERA_KEY_JPEG_HEIGHT   "jpeg_height"
#define SAMPLE_CAMERA_KEY_JPEG_QUALITY  "jpeg_quality"
#define SAMPLE_CAMERA_KEY_JPEG_THUMB_WIDTH    "jpeg_thumb_width"
#define SAMPLE_CAMERA_KEY_JPEG_THUMB_HEIGHT   "jpeg_thumb_height"
#define SAMPLE_CAMERA_KEY_JPEG_THUMB_QUALITY  "jpeg_thumb_quality"
#define SAMPLE_CAMERA_KEY_JPEG_THUMBFILE_FLAG "jpeg_thumbfile_flag"
#define SAMPLE_CAMERA_KEY_JPEG_NUM      "jpeg_num"
#define SAMPLE_CAMERA_KEY_JPEG_INTERVAL "jpeg_interval"
#define SAMPLE_CAMERA_KEY_JPEG_FOLDER   "jpeg_folder"

#define SAMPLE_CAMERA_KEY_JPEG_REGION_OVERLAY_X   "jpeg_region_overlay_x"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_OVERLAY_Y   "jpeg_region_overlay_y"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_OVERLAY_W   "jpeg_region_overlay_w"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_OVERLAY_H   "jpeg_region_overlay_h"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_OVERLAY_PRIORITY   "jpeg_region_overlay_priority"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_OVERLAY_INVERT   "jpeg_region_overlay_invert"

#define SAMPLE_CAMERA_KEY_JPEG_REGION_COVER_X   "jpeg_region_cover_x"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_COVER_Y   "jpeg_region_cover_y"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_COVER_W   "jpeg_region_cover_w"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_COVER_H   "jpeg_region_cover_h"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_COVER_COLOR   "jpeg_region_cover_color"
#define SAMPLE_CAMERA_KEY_JPEG_REGION_COVER_PRIORITY   "jpeg_region_cover_priority"

#define SAMPLE_CAMERA_KEY_OSD1_TYPE     "osd1_type"
#define SAMPLE_CAMERA_KEY_OSD1_PRIORITY "osd1_priority"
#define SAMPLE_CAMERA_KEY_OSD1_COLOR    "osd1_color"
#define SAMPLE_CAMERA_KEY_OSD1_COLOR_INVERT    "osd1_color_invert"
#define SAMPLE_CAMERA_KEY_OSD1_INVERT_LUM_THRESH    "osd1_invert_lum_thresh"
#define SAMPLE_CAMERA_KEY_OSD1_INVERT_UNIT_WIDTH    "osd1_invert_unit_width"
#define SAMPLE_CAMERA_KEY_OSD1_INVERT_UNIT_HEIGHT   "osd1_invert_unit_height"
#define SAMPLE_CAMERA_KEY_OSD1_X        "osd1_x"
#define SAMPLE_CAMERA_KEY_OSD1_Y        "osd1_y"
#define SAMPLE_CAMERA_KEY_OSD1_W        "osd1_w"
#define SAMPLE_CAMERA_KEY_OSD1_H        "osd1_h"

#define SAMPLE_CAMERA_KEY_OSD2_TYPE     "osd2_type"
#define SAMPLE_CAMERA_KEY_OSD2_PRIORITY "osd2_priority"
#define SAMPLE_CAMERA_KEY_OSD2_COLOR    "osd2_color"
#define SAMPLE_CAMERA_KEY_OSD2_COLOR_INVERT    "osd2_color_invert"
#define SAMPLE_CAMERA_KEY_OSD2_INVERT_LUM_THRESH    "osd2_invert_lum_thresh"
#define SAMPLE_CAMERA_KEY_OSD2_INVERT_UNIT_WIDTH    "osd2_invert_unit_width"
#define SAMPLE_CAMERA_KEY_OSD2_INVERT_UNIT_HEIGHT   "osd2_invert_unit_height"
#define SAMPLE_CAMERA_KEY_OSD2_X        "osd2_x"
#define SAMPLE_CAMERA_KEY_OSD2_Y        "osd2_y"
#define SAMPLE_CAMERA_KEY_OSD2_W        "osd2_w"
#define SAMPLE_CAMERA_KEY_OSD2_H        "osd2_h"

#define SAMPLE_CAMERA_KEY_OSD3_TYPE     "osd3_type"
#define SAMPLE_CAMERA_KEY_OSD3_PRIORITY "osd3_priority"
#define SAMPLE_CAMERA_KEY_OSD3_COLOR    "osd3_color"
#define SAMPLE_CAMERA_KEY_OSD3_COLOR_INVERT    "osd3_color_invert"
#define SAMPLE_CAMERA_KEY_OSD3_INVERT_LUM_THRESH    "osd3_invert_lum_thresh"
#define SAMPLE_CAMERA_KEY_OSD3_INVERT_UNIT_WIDTH    "osd3_invert_unit_width"
#define SAMPLE_CAMERA_KEY_OSD3_INVERT_UNIT_HEIGHT   "osd3_invert_unit_height"
#define SAMPLE_CAMERA_KEY_OSD3_X        "osd3_x"
#define SAMPLE_CAMERA_KEY_OSD3_Y        "osd3_y"
#define SAMPLE_CAMERA_KEY_OSD3_W        "osd3_w"
#define SAMPLE_CAMERA_KEY_OSD3_H        "osd3_h"

#define SAMPLE_CAMERA_KEY_TEST_DURATION     "test_duration"

#endif  /* _SAMPLE_CAMERA_CONFIG_H_ */

