include_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}/include/algo_aw/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/rtsp/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/config/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/media/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/sample/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/config/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/media/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/net/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/include/media/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/include/media/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/include/net/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/include/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/LIBRARY/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/AudioLib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/aec_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/agc_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/ans_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/drc_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include_FsWriter/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include_demux/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include_muxer/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include_stream/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libADAS/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libISE/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libMODSoft/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libResample/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/lib_aw_ai_core/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/lib_aw_ai_mt/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libcedarc/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libcedarx/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libisp/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/textEncLib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/AudioLib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/midware/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/osal/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/AudioLib/midware/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/decoding/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/encoding/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/AudioLib/midware/decoding/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/AudioLib/midware/decoding/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/AudioLib/midware/encoding/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/AudioLib/midware/encoding/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/AudioLib/osal/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/aec_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/aec_lib/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/agc_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/agc_lib/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/ans_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/drc_lib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/drc_lib/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/include_FsWriter/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/include_demux/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/include_muxer/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/include_stream/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libADAS/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libADAS/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libISE/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libISE/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libMODSoft/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libMODSoft/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libResample/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libResample/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/lib_aw_ai_core/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/lib_aw_ai_core/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/lib_aw_ai_mt/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/lib_aw_ai_mt/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libcedarc/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libcedarc/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libcedarx/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libcore/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libcedarx/libcore/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/common/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libcedarx/libcore/common/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/iniparser/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libcedarx/libcore/common/iniparser/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libisp/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/isp_dev/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/isp_tuning/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libisp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/V4l2Camera/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/device/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libisp/include/V4l2Camera/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/linux/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libisp/include/V4l2Camera/linux/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libisp/include/device/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libisp/isp_dev/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/libisp/isp_tuning/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/textEncLib/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/LIBRARY/textEncLib/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/audio/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/component/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include_render/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/videoIn/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/include/audio/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/include/component/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/include/include_render/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/include/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/media/include/videoIn/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/sample/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/configfileparser/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/middleware/sample/configfileparser/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/public/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/libion/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/rgb_ctrl/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/smartlink/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/crypto/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/cutils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/database/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/hardware/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/log/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/lua/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/openssl/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/sys/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/tinyhttp/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/vo/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/wifi/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/crypto/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/cutils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/database/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/hardware/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/log/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/lua/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/openssl/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/sys/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/tinyhttp/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/utils/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/vo/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/include/wifi/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/libion/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/libion/include/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/rgb_ctrl/
    ${CMAKE_CURRENT_SOURCE_DIR}/include/mpp/system/public/smartlink/
)