#!/bin/sh

name=`basename $0`

usage() {
  echo "$name Usage:"
  echo ""
  echo "$name [function]"
  echo "function: mtp,    support MTP function"
  echo "          adb,    support adb function"
  echo "          rndis,  support rndis function"
  echo "          adb,mtp support adb and mtp function"
  echo "example:"
  echo "$name adb,mtp"
  echo ""
}

udc_controller=`ls /sys/class/udc`

set_usb_function() {
# 1:function
# 2:idVendor
# 3:idProduct
#

  [ -d /sys/kernel/config/usb_gadget ] || {
	mount -t configfs none /sys/kernel/config
	mkdir /sys/kernel/config/usb_gadget/g1
	mkdir /sys/kernel/config/usb_gadget/g1/strings/0x409
	echo "Allwinner Technology Inc." > /sys/kernel/config/usb_gadget/g1/strings/0x409/manufacturer
	echo "Tina" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
  }
  [ -d /sys/kernel/config/usb_gadget/g1/configs/c.1 ] || {
	mkdir /sys/kernel/config/usb_gadget/g1/configs/c.1
	echo 0xc0 > /sys/kernel/config/usb_gadget/g1/configs/c.1/bmAttributes
	echo 500 > /sys/kernel/config/usb_gadget/g1/configs/c.1/MaxPower
	mkdir /sys/kernel/config/usb_gadget/g1/configs/c.1/strings/0x409
  }

  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/ffs.adb
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/mtp.gs0
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/f1
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/rndis.usb0
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/uac1.usb0
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/accessory.usb0
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/hid.usb0
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/loopback.usb0
  rm -f /sys/kernel/config/usb_gadget/g1/configs/c.1/gser.usb0

  echo $2 > /sys/kernel/config/usb_gadget/g1/idVendor
  echo $3 > /sys/kernel/config/usb_gadget/g1/idProduct

  if [ $1 == "none" ]; then
	return
  elif [ $1 == "mtp" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/mtp.gs0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/mtp.gs0
	}
	echo "Tina MTP" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
	ln -s /sys/kernel/config/usb_gadget/g1/functions/mtp.gs0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/mtp.gs0
  elif [ $1 == "adb" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/ffs.adb ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/ffs.adb
	}
	echo "Tina ADB" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
	ln -s /sys/kernel/config/usb_gadget/g1/functions/ffs.adb/ /sys/kernel/config/usb_gadget/g1/configs/c.1/ffs.adb
  elif [ $1 == "mass_storage" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/mass_storage.usb0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/mass_storage.usb0
		echo Tina > /sys/kernel/config/usb_gadget/g1/functions/mass_storage.usb0/lun.0/inquiry_string
	}
	ln -s /sys/kernel/config/usb_gadget/g1/functions/mass_storage.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/f1
  elif [ $1 == "mtp,adb" ]; then
	ln -s /sys/kernel/config/usb_gadget/g1/functions/ffs.adb/ /sys/kernel/config/usb_gadget/g1/configs/c.1/ffs.adb
	ln -s /sys/kernel/config/usb_gadget/g1/functions/mtp.gs0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/mtp.gs0
  elif [ $1 == "mass_storage,adb" ]; then
	ln -s /sys/kernel/config/usb_gadget/g1/functions/ffs.adb/ /sys/kernel/config/usb_gadget/g1/configs/c.1/ffs.adb
	ln -s /sys/kernel/config/usb_gadget/g1/functions/mass_storage.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/f1
  elif [ $1 == "rndis" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/rndis.usb0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/rndis.usb0
	}
	ln -s /sys/kernel/config/usb_gadget/g1/functions/rndis.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/rndis.usb0
  elif [ $1 == "uac1" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0
		# lack of ISO(IN) endpoint, disable PC capture
		echo 0 > /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0/c_chmask
		# support capture and playback
		#echo 0x3 > /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0/c_chmask
		#echo 0x3 > /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0/p_chmask
		#echo 16000 > /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0/p_srate
		#echo 48000 > /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0/c_srate
	}
	echo "Tina UAC1" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
	ln -s /sys/kernel/config/usb_gadget/g1/functions/uac1.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/uac1.usb0
  elif [ $1 == "accessory" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/accessory.usb0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/accessory.usb0
	}
	echo "Tina Accessory" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
	ln -s /sys/kernel/config/usb_gadget/g1/functions/accessory.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/accessory.usb0
  elif [ $1 == "hid" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/hid.usb0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/hid.usb0
	}
	echo "Tina Keyboard" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
	echo 1 > /sys/kernel/config/usb_gadget/g1/functions/hid.usb0/protocol
	echo 8 > /sys/kernel/config/usb_gadget/g1/functions/hid.usb0/report_length
	echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > /sys/kernel/config/usb_gadget/g1/functions/hid.usb0/report_desc
	ln -s /sys/kernel/config/usb_gadget/g1/functions/hid.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/hid.usb0
  elif [ $1 == "loopback" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/loopback.usb0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/loopback.usb0
	}
	echo "Tina Loopback" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
	ln -s /sys/kernel/config/usb_gadget/g1/functions/loopback.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/loopback.usb0
  elif [ $1 == "gser" ]; then
	[ -d /sys/kernel/config/usb_gadget/g1/functions/gser.usb0 ] || {
		mkdir /sys/kernel/config/usb_gadget/g1/functions/gser.usb0
	}
	echo "Gadget Serial" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
	ln -s /sys/kernel/config/usb_gadget/g1/functions/gser.usb0/ /sys/kernel/config/usb_gadget/g1/configs/c.1/gser.usb0
  fi

  [ -d /dev/usb-ffs/adb ] || {
	mkdir /dev/usb-ffs
	mkdir /dev/usb-ffs/adb
	mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb/
  }
  echo $udc_controller > /sys/kernel/config/usb_gadget/g1/UDC
}

# idVendor, idProduct only for test

if [ $# == 1 ]; then
  if [ $1 == "none" ]; then
    set_usb_function none 0x1f3a 0x1001
    return
  fi
  if [ $1 == "adb" ]; then
    set_usb_function adb 0x18d1 0xD002
    return
  fi
  if [ $1 == "mtp" ]; then
    set_usb_function mtp 0x1f3a 0x1006
    return
  fi
  if [ $1 == "rndis" ]; then
    set_usb_function rndis 0x0525 0xa4a2
    return
  fi
  if [ $1 == "uac1" ]; then
    set_usb_function uac1 0x1d61 0x0101
    return
  fi
  if [ $1 == "mass_storage" ]; then
    set_usb_function mass_storage 0x1f3a 0x1000
    return
  fi
  if [ $1 == "accessory" ]; then
    set_usb_function accessory 0x1f3a 0x2d00
    return
  fi
  if [ $1 == "hid" ]; then
    set_usb_function hid 0x0525 0xa4ac
    return
  fi
  if [ $1 == "loopback" ]; then
    set_usb_function loopback 0x1f3a 0xd002
    return
  fi
  if [ $1 == "gser" ]; then
    #set_usb_function gser 0x0525 0xa4a6
    set_usb_function gser 0x067b 0x2303
    return
  fi
  if [ $1 == "adb,mtp" -o $1 == "mtp,adb" ]; then
    set_usb_function mtp,adb 0x1f3a 0x1007
    return
  fi
  if [ $1 == "adb,mass_storage" -o $1 == "mass_storage,adb" ]; then
    set_usb_function mass_storage,adb 0x1f3a 0x1002
    return
  fi
  echo "Invalid arg:$1"
  usage
else
  echo "Lack of arg!"
  usage
fi
