
#ifndef _SAMPLE_RECORDERSEGMENT_CONFIG_H_
#define _SAMPLE_RECORDERSEGMENT_CONFIG_H_

#define SAMPLE_RECORDERSEGMENT_KEY_CAPTURE_WIDTH    "capture_width"
#define SAMPLE_RECORDERSEGMENT_KEY_CAPTURE_HEIGHT   "capture_height"
#define SAMPLE_RECORDERSEGMENT_KEY_PIC_FORMAT       "pic_format"
#define SAMPLE_RECORDERSEGMENT_KEY_FRAME_RATE       "frame_rate"
#define SAMPLE_RECORDERSEGMENT_KEY_DISP_WIDTH       "disp_width"
#define SAMPLE_RECORDERSEGMENT_KEY_DISP_HEIGHT      "disp_height"

#define SAMPLE_RECORDERSEGMENT_KEY_ENCODE_TYPE      "encode_type"
#define SAMPLE_RECORDERSEGMENT_KEY_AUDIO_ENCODE_TYPE "audio_encode_type"
#define SAMPLE_RECORDERSEGMENT_KEY_ENCODE_WIDTH     "encode_width"
#define SAMPLE_RECORDERSEGMENT_KEY_ENCODE_HEIGHT    "encode_height"
#define SAMPLE_RECORDERSEGMENT_KEY_ENCODE_BITRATE   "encode_bitrate"
#define SAMPLE_RECORDERSEGMENT_KEY_FILE_DURATION_POLICY "file_duration_policy"

#define SAMPLE_RECORDERSEGMENT_KEY_SEGMENT_FOLDER   "segment_folder"
#define SAMPLE_RECORDERSEGMENT_KEY_SEGMENT_COUNT    "segment_count"
#define SAMPLE_RECORDERSEGMENT_KEY_SEGMENT_METHOD   "segment_method"
#define SAMPLE_RECORDERSEGMENT_KEY_SEGMENT_DURATION "segment_duration"
#define SAMPLE_RECORDERSEGMENT_KEY_SEGMENT_SIZE     "segment_size"

#define SAMPLE_RECORDERSEGMENT_KEY_JPEG_WIDTH           "jpeg_width"
#define SAMPLE_RECORDERSEGMENT_KEY_JPEG_HEIGHT          "jpeg_height"
#define SAMPLE_RECORDERSEGMENT_KEY_JPEG_THUMB_WIDTH     "jpeg_thumb_width"
#define SAMPLE_RECORDERSEGMENT_KEY_JPEG_THUMB_HEIGHT    "jpeg_thumb_height"
#define SAMPLE_RECORDERSEGMENT_KEY_JPEG_NUM             "jpeg_num"
#define SAMPLE_RECORDERSEGMENT_KEY_JPEG_INTERVAL        "jpeg_interval"

#endif  /* _SAMPLE_RECORDERSEGMENT_CONFIG_H_ */

