#ifndef __SAMPLE_RECORDMULTISTREAM_CONFIG_H__
#define __SAMPLE_RECORDMULTISTREAM_CONFIG_H__

#define SAMPLE_RECORDMULTISTREAM_KEY_CAPTURE_WIDTH     "capture_width"
#define SAMPLE_RECORDMULTISTREAM_KEY_CAPTURE_HEIGHT    "capture_height"
#define SAMPLE_RECORDMULTISTREAM_KEY_VI_CLOCK          "vi_clock"
#define SAMPLE_RECORDMULTISTREAM_KEY_VE_CLOCK          "ve_clock"
#define SAMPLE_RECORDMULTISTREAM_KEY_CAPTURE_FORMAT    "capture_format"
#define SAMPLE_RECORDMULTISTREAM_KEY_PREVIEW_WIDTH     "preview_width"
#define SAMPLE_RECORDMULTISTREAM_KEY_PREVIEW_HEIGHT    "preview_height"
#define SAMPLE_RECORDMULTISTREAM_KEY_PREVIEW_FORMAT    "preview_format"
#define SAMPLE_RECORDMULTISTREAM_KEY_DIGITAL_ZOOM      "digital_zoom"
#define SAMPLE_RECORDMULTISTREAM_KEY_DISP_WIDTH        "disp_width"
#define SAMPLE_RECORDMULTISTREAM_KEY_DISP_HEIGHT       "disp_height"

#define SAMPLE_RECORDMULTISTREAM_KEY_PREVIEW_ENABLE    "preview_enable"
#define SAMPLE_RECORDMULTISTREAM_KEY_FRAME_RATE        "frame_rate"

//first venc
#define SAMPLE_RECORDMULTISTREAM_KEY_VIPP_0              "Vipp0"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_TYPE_0       "encode_type_0"
#define SAMPLE_RECORDMULTISTREAM_KEY_DST_FRAMERATE_0     "dst_framerate_0"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_WIDTH_0     "encode_width_0"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_HEIGHT_0    "encode_height_0"
#define SAMPLE_RECORDMULTISTREAM_KEY_IDRFRAME_INTERVAL_0 "IDRFrame_interval_0"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_BITRATE_0   "encode_bitrate_0"
#define SAMPLE_RECORDMULTISTREAM_KEY_ONLINE_ENABLE_0    "online_en_0"
#define SAMPLE_RECORDMULTISTREAM_KEY_ONLINE_SHARE_BUF_NUM_0   "online_share_buf_num_0"

//second venc
#define SAMPLE_RECORDMULTISTREAM_KEY_VIPP_1              "Vipp1"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_TYPE_1       "encode_type_1"
#define SAMPLE_RECORDMULTISTREAM_KEY_DST_FRAMERATE_1     "dst_framerate_1"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_WIDTH_1     "encode_width_1"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_HEIGHT_1    "encode_height_1"
#define SAMPLE_RECORDMULTISTREAM_KEY_IDRFRAME_INTERVAL_1 "IDRFrame_interval_1"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_BITRATE_1   "encode_bitrate_1"

#define SAMPLE_RECORDMULTISTREAM_KEY_AUDIO_ENCODE_TYPE     "audio_encode_type"
#define SAMPLE_RECORDMULTISTREAM_KEY_AUDIO_SAMPLE_RATE     "audio_sample_rate"
#define SAMPLE_RECORDMULTISTREAM_KEY_AUDIO_CHANNEL_NUM     "audio_channel_num"
#define SAMPLE_RECORDMULTISTREAM_KEY_AUDIO_ENCODE_BITRATE  "audio_encode_bitrate"

#define SAMPLE_RECORDMULTISTREAM_KEY_SEGMENT_COUNT      "segment_count"
#define SAMPLE_RECORDMULTISTREAM_KEY_SEGMENT_DURATION   "segment_duration"

#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_DURATION   "encode_duration"
#define SAMPLE_RECORDMULTISTREAM_KEY_ENCODE_FOLDER     "encode_folder"

#define SAMPLE_RECORDMULTISTREAM_KEY_FILE_NAME        "file_name"

#define SAMPLE_RECORDMULTISTREAM_MUX_CACHE_ENABLE        "mux_cache_enable"
#define SAMPLE_RECORDMULTISTREAM_MUX_CACHE_STRM_IDS_FILTER_ENABLE        "mux_cache_strm_ids_filter_enable"

#endif  /* __SAMPLE_RECORDMULTISTREAM_CONFIG_H__ */
