
#ifndef _SAMPLE_ENCODERESOLUTIONCHANGE_CONFIG_H_
#define _SAMPLE_ENCODERESOLUTIONCHANGE_CONFIG_H_

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_CAPTURE_WIDTH     "capture_width"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_CAPTURE_HEIGHT    "capture_height"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_VI_CLOCK          "vi_clock"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_VE_CLOCK          "ve_clock"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_CAPTURE_FORMAT    "capture_format"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_PREVIEW_WIDTH     "preview_width"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_PREVIEW_HEIGHT    "preview_height"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_PREVIEW_FORMAT    "preview_format"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_DIGITAL_ZOOM      "digital_zoom"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_DISP_WIDTH        "disp_width"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_DISP_HEIGHT       "disp_height"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_PREVIEW_ENABLE    "preview_enable"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_FRAME_RATE        "frame_rate"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_DST_FRAME_RATE    "dst_frame_rate"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_TYPE       "encode_type"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_H264_PROFILE      "h264_profile"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_H264_LEVEL        "h264_level"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_H265_PROFILE      "h265_profile"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_H265_LEVEL        "h265_level"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_WIDTH0     "encode_width0"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_HEIGHT0    "encode_height0"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_WIDTH1     "encode_width1"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_HEIGHT1    "encode_height1"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_IDRFRAME_INTERVAL "IDRFrame_interval"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_VIDEOENCODINGPINTRA       "VideoEncodingPIntra"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_RC_MODE           "rc_mode"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_QP1               "Qp1"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_QP2               "Qp2"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_BITRATE0   "encode_bitrate0"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_BITRATE1   "encode_bitrate1"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_GOP_MODE          "gop_mode"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_SPINTERVAL        "SPInterval"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_VIRTUALIFRAME_INTERVAL    "VirtualIFrame_interval"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ADVANCEDREF_ENABLE        "AdvancedRef_enable"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_NBASE                     "nBase"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_NENHANCE                  "nEnhance"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_BREFBASEEN                "bRefBaseEn"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_HORIZONFLIP               "horizonflip"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ADAPTIVEINTRAINP          "adaptiveintrainp"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_3DNR                      "b3dnr"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_COLOR2GREY                "color2grey"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_NULLSKIP                  "nullSkip"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_SMARTP                "smartP"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_INTRAREFRESHBLOCKNUM    "IntraRefreshBlockNum"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_TIMELAPSE_FPS     "time_lapse_fps"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_SUPER_FRM_MODE        "SuperFrmMode"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_SUPER_IFRM_BITSTHR    "SuperIFrmBitsThr"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_SUPER_PFRM_BITSTHR    "SuperPFrmBitsThr"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_AUDIO_ENCODE_TYPE     "audio_encode_type"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_AUDIO_SAMPLE_RATE     "audio_sample_rate"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_AUDIO_CHANNEL_NUM     "audio_channel_num"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_AUDIO_ENCODE_BITRATE  "audio_encode_bitrate"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_DURATION   "encode_duration"
#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_ENCODE_FOLDER     "encode_folder"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_FILE_PATH0        "file_path0"

#define SAMPLE_ENCODERESOLUTIONCHANGE_KEY_FILE_PATH1        "file_path1"

#endif  /* _SAMPLE_ENCODERESOLUTIONCHANGE_CONFIG_H_ */

