subdir-ccflags-y += 	-I$(srctree)/include/melis/kernel/rtos/zephyr \
			-I$(srctree)/ekernel/core/zephyr/kernel/include \
			-I$(srctree)/include/melis/kernel/rtos/zephyr/arch \
			-I$(srctree)/include/melis/kernel/rtos/zephyr/arch/arm/cortex_m

obj-y += kernel/
obj-y += misc/
obj-y += offsets/
