subdir-ccflags-y += -I$(srctree)/ekernel/subsys/aw/multi_console \
                    -I$(srctree)/ekernel/drivers/include/drv \
                    -I$(srctree)/include/melis/libs
obj-y += syscalls.o
obj-y += libc_sym.o
obj-y += libc.o
obj-y += stdio.o
