#ifndef _SAMPLE_RECORDSWITCHFILENORMAL_CONFIG_H_
#define _SAMPLE_RECORDSWITCHFILENORMAL_CONFIG_H_

#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_MAIN_VIPP_WIDTH    "main_vipp_width"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_MAIN_VIPP_HEIGHT   "main_vipp_height"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SUB_VIPP_WIDTH     "sub_vipp_width"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SUB_VIPP_HEIGHT    "sub_vipp_height"

#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_PIC_FORMAT       "pic_format"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_FRAME_RATE       "frame_rate"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_ENCODE_TYPE      "encode_type"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_AUDIO_ENCODE_TYPE "audio_encode_type"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_MAIN_ENCODE_WIDTH     "main_encode_width"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_MAIN_ENCODE_HEIGHT    "main_encode_height"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_MAIN_ENCODE_BITRATE   "main_encode_bitrate"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SUB_ENCODE_WIDTH     "sub_encode_width"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SUB_ENCODE_HEIGHT    "sub_encode_height"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SUB_ENCODE_BITRATE   "sub_encode_bitrate"

#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SEGMENT_FOLDER   "segment_folder"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SEGMENT_COUNT    "segment_count"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SEGMENT_METHOD   "segment_method"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SEGMENT_DURATION "segment_duration"
#define SAMPLE_RECORDSWITCHFILENORMAL_KEY_SEGMENT_SIZE     "segment_size"

#endif  /* _SAMPLE_RECORDSWITCHFILENORMAL_CONFIG_H_ */

