
#ifndef _SAMPLE_RECORDLOWDELAY_CONFIG_H_
#define _SAMPLE_RECORDLOWDELAY_CONFIG_H_

#define SAMPLE_RECORDLOWDELAY_KEY_CAPTURE_WIDTH    "capture_width"
#define SAMPLE_RECORDLOWDELAY_KEY_CAPTURE_HEIGHT   "capture_height"
#define SAMPLE_RECORDLOWDELAY_KEY_CAPTURE_FORMAT   "capture_format"
#define SAMPLE_RECORDLOWDELAY_KEY_PREVIEW_WIDTH    "preview_width"
#define SAMPLE_RECORDLOWDELAY_KEY_PREVIEW_HEIGHT   "preview_height"
#define SAMPLE_RECORDLOWDELAY_KEY_PREVIEW_FORMAT   "preview_format"

#define SAMPLE_RECORDLOWDELAY_KEY_PREVIEW_ENABLE   "preview_enable"
#define SAMPLE_RECORDLOWDELAY_KEY_ENCODE_ENABLE    "encode_enable"
#define SAMPLE_RECORDLOWDELAY_KEY_FRAME_RATE       "frame_rate"
#define SAMPLE_RECORDLOWDELAY_KEY_DISPLAY_FRAME_RATE   "display_frame_rate"
#define SAMPLE_RECORDLOWDELAY_KEY_CAPTURE_BUF_NUM  "capture_buf_num"
#define SAMPLE_RECORDLOWDELAY_KEY_PREVIEW_BUF_NUM  "preview_buf_num"
#define SAMPLE_RECORDLOWDELAY_KEY_ENCODE_TYPE      "encode_type"

#define SAMPLE_RECORDLOWDELAY_KEY_ENCODE_WIDTH     "encode_width"
#define SAMPLE_RECORDLOWDELAY_KEY_ENCODE_HEIGHT    "encode_height"
#define SAMPLE_RECORDLOWDELAY_KEY_ENCODE_BITRATE   "encode_bitrate"

#define SAMPLE_RECORDLOWDELAY_KEY_ENCODE_DURATION  "encode_duration"
#define SAMPLE_RECORDLOWDELAY_KEY_CALLBACK_FLAG    "callback_flag"
#define SAMPLE_RECORDLOWDELAY_KEY_ENCODE_FOLDER    "encode_folder"
#define SAMPLE_RECORDLOWDELAY_KEY_CALLBACK_FILE_PATH    "callback_file_path"
#define SAMPLE_RECORDLOWDELAY_KEY_FILE_PATH2       "file_path2"

#endif  /* _SAMPLE_RECORDLOWDELAY_CONFIG_H_ */

